version: '3.8'

services:
  # Сервис PostgreSQL
  postgres:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: building_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  # Сервис с Go-приложением
  app:
    build: .
    container_name: go_app
    environment:
      DB_HOST: postgres_container
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: building_service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
