version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - HOST=db
      - PORT=5432
      - USER=postgres
      - PASSWORD=12345678
      - DBNAME=building_service
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: building_service
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
